"""add password_hash column

Revision ID: 6eebbf6d52e4
Revises: 
Create Date: 2026-05-18 21:06:52.935908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6eebbf6d52e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'name')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
